name: Create Baseline
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.3
        coverage: none # disable xdebug, pcov

    - run: composer require phpstan/phpstan
      name: Install PHPStan
      
    - run: vendor/bin/phpstan analyse --configuration=phpstan.neon --generate-baseline .github/workflows/phpstan-baseline.neon
      name: PHPStan
    - run: cat .github/workflows/phpstan-baseline.neon
